// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unmvdntddrkutnmmxzzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVubXZkbnRkZHJrdXRubW14enpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5ODA1MTksImV4cCI6MjA2NDU1NjUxOX0.s5PWfCeBLvqQe5E9LOXrc8Qyugogp8m72GVh-YnwaC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);